# Render Blueprint Specification
# Doc: https://render.com/docs/blueprints

services:
  - type: web
    name: rollercoinmarkt-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BEARER_TOKEN
        sync: false # Render will prompt you to enter your BEARER_TOKEN value in the dashboard
